version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      # Exécute les tests unitaires
      - run:
          name: Test
          command: mvn verify

      # Exécute Checkstyle et génère le rapport HTML
      - run:
          name: Checkstyle
          command: |
            sudo apt-get update
            sudo apt-get install -y checkstyle
            checkstyle -c checkstyle.xml src/main/java
            # Génère le rapport HTML dans le répertoire checkstyle-report
            checkstyle -c checkstyle.xml -f html -o checkstyle-report/checkstyle.html src/main/java

      # Persiste le rapport HTML comme artefact
      - persist_to_workspace:
          root: .
          paths:
            - checkstyle-report

workflows:
  sample:
    jobs:
      - build-and-test
