version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      # Exécute les tests unitaires
      - run:
          name: Test
          command: mvn verify

      # Génère la Javadoc
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Exécute Checkstyle
      - run:
          name: Checkstyle
          command: |
            sudo apt-get update
            sudo apt-get install -y checkstyle
            checkstyle -c checkstyle.xml src/main/java

      # Déploie la Javadoc sur GitHub Pages
      - run:
          name: DeployJavadoc
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            mv target/site/apidocs/* .
            git init
            git add .
            git commit -m "Deploy Javadoc"
            git checkout -b gh-pages
            git push --force "https://github.com/your-username/your-repo.git" gh-pages
