name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - master  # Remplacez "main" par le nom de votre branche principale si nécessaire

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Vos étapes de test ici. Assurez-vous de générer un rapport de couverture.

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: FlorianLAMBER/ceri-m1-techniques-de-test
